import re

def validate_password(password: str) -> bool:
    """
    Validate the strength of a password.
    Rules enforced:
    - Minimum length of 8 characters.
    - Contains at least one digit (0-9).
    - Contains at least one uppercase ASCII letter (A-Z).
    - Contains at least one special character from the set: ! @ # $.
    Parameters
    ----------
    password : str
        The password string to validate.
    Returns
    -------
    bool
        True if the password meets all requirements, False otherwise.
    Examples
    --------
    >>> validate_password("Secure1!")
    True
    >>> validate_password("weakpass")
    False
    """
    # Regex checks generated by AI:
    has_digit = re.search(r"\d", password)
    has_upper = re.search(r"[A-Z]", password)
    has_special = re.search(r"[!@#$]", password)

    # Step-by-step validation
    if len(password) < 8:
        return False
    if not has_digit:
        return False
    if not has_upper:
        return False
    if not has_special:
        return False

    return True


# -------- Dynamic Input Demo --------
if __name__ == "__main__":
    user_pw = input("Enter password to validate: ")
    if validate_password(user_pw):
        print("Password is valid ✔️")
    else:
        print("Password is INVALID ❌")


# -------- Pytest Test Cases --------
def test_valid_password():
    assert validate_password("Strong1!") is True

def test_missing_digit():
    assert validate_password("Strong!!") is False

def test_missing_uppercase():
    assert validate_password("weak1!") is False

def test_missing_special():
    assert validate_password("Strong11") is False

def test_too_short():
    assert validate_password("S1!") is False
